services:
  postgres:
    image: postgres:17-alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - ./deploy/compose/initdb:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]

  usersvc:
    build:
      context: .
      dockerfile: usersvc/Dockerfile
    environment:
      DB_DSN: postgres://app:app@postgres:5432/users_db?sslmode=disable
      GRPC_ADDR: :50051
    depends_on: [postgres]
    ports: ["50051:50051"]

  ordersvc:
    build:
      context: .
      dockerfile: ordersvc/Dockerfile
    environment:
      DB_DSN: postgres://app:app@postgres:5432/orders_db?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      GRPC_ADDR: :50052
    depends_on: [postgres, rabbitmq]
    ports: ["50052:50052"]

  paymentsvc:
    build: ./paymentsvc
    environment:
      DB_URL: postgres://app:app@postgres:5432/payments_db?sslmode=disable
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on: [postgres, rabbitmq]

  gateway:
    build: ./gateway
    environment:
      USERSVC_ADDR: usersvc:50051
      ORDERSVC_ADDR: ordersvc:50052
      HTTP_ADDR: :8080
    depends_on: [usersvc, ordersvc]
    ports: ["8080:8080"]
