// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: events/v1/order_event.proto

package eventsv1

import (
	v1 "github.com/Daniel-Sogbey/micro-weekend/proto/order/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentStatus v1.Status              `protobuf:"varint,4,opt,name=payment_status,json=paymentStatus,proto3,enum=order.v1.Status" json:"payment_status,omitempty"`
	CreatedUnix   int64                  `protobuf:"varint,5,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_events_v1_order_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_order_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_order_event_proto_rawDescGZIP(), []int{0}
}

func (x *OrderEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderEvent) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *OrderEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderEvent) GetPaymentStatus() v1.Status {
	if x != nil {
		return x.PaymentStatus
	}
	return v1.Status(0)
}

func (x *OrderEvent) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

var File_events_v1_order_event_proto protoreflect.FileDescriptor

const file_events_v1_order_event_proto_rawDesc = "" +
	"\n" +
	"\x1bevents/v1/order_event.proto\x12\tevents.v1\x1a\x14order/v1/order.proto\"\xbf\x01\n" +
	"\n" +
	"OrderEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x127\n" +
	"\x0epayment_status\x18\x04 \x01(\x0e2\x10.order.v1.StatusR\rpaymentStatus\x12!\n" +
	"\fcreated_unix\x18\x05 \x01(\x03R\vcreatedUnixBAZ?github.com/Daniel-Sogbey/micro-weekend/proto/events/v1;eventsv1b\x06proto3"

var (
	file_events_v1_order_event_proto_rawDescOnce sync.Once
	file_events_v1_order_event_proto_rawDescData []byte
)

func file_events_v1_order_event_proto_rawDescGZIP() []byte {
	file_events_v1_order_event_proto_rawDescOnce.Do(func() {
		file_events_v1_order_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_order_event_proto_rawDesc), len(file_events_v1_order_event_proto_rawDesc)))
	})
	return file_events_v1_order_event_proto_rawDescData
}

var file_events_v1_order_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_order_event_proto_goTypes = []any{
	(*OrderEvent)(nil), // 0: events.v1.OrderEvent
	(v1.Status)(0),     // 1: order.v1.Status
}
var file_events_v1_order_event_proto_depIdxs = []int32{
	1, // 0: events.v1.OrderEvent.payment_status:type_name -> order.v1.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_v1_order_event_proto_init() }
func file_events_v1_order_event_proto_init() {
	if File_events_v1_order_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_order_event_proto_rawDesc), len(file_events_v1_order_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_order_event_proto_goTypes,
		DependencyIndexes: file_events_v1_order_event_proto_depIdxs,
		MessageInfos:      file_events_v1_order_event_proto_msgTypes,
	}.Build()
	File_events_v1_order_event_proto = out.File
	file_events_v1_order_event_proto_goTypes = nil
	file_events_v1_order_event_proto_depIdxs = nil
}
